// Generated by BuildPilot from the validated call transcript for Antalia Restaurant.
// Do not hand-edit business data here across rebuilds — update the source
// requirements and regenerate instead. See src/types/site-config.ts (starter
// template) for the full SiteConfig shape (cinematic or plain variant) and
// docs/DEVIN_3D_WEBSITE_SPEC.md for how each field is used.
import type { SiteConfig } from "./types/site-config";

export const siteConfig: SiteConfig = {
  "variant": "cinematic",
  "businessName": "Antalia Restaurant",
  "purpose": "Levantine grill restaurant in Al Quoz, Dubai",
  "targetAudience": "families, office workers, and delivery customers",
  "contact": {
    "address": "Al Quoz, Dubai"
  },
  "palette": {
    "background": "#0B0A08",
    "surface": "#1C1410",
    "text": "#F9F0E6",
    "muted": "#C7B7A1",
    "accent": "#E07A5F",
    "accentHover": "#D0674A"
  },
  "enquirySection": {
    "id": "enquiry",
    "eyebrow": "Questions? Let us chat",
    "heading": "Plan your visit or your event with Antalia",
    "body": "We are here to help with dine-in reservations, catering details, and menu custom requests. Tell us how we can make your experience memorable.",
    "submitLabel": "Send enquiry",
    "enquiryTypes": [
      "General Inquiry",
      "Catering Request",
      "Menu Customization",
      "Delivery Details"
    ],
    "disconnectedMessage": "Form submission is not connected yet.",
    "consentLabel": "I agree to be contacted about my inquiry."
  },
  "navigation": [
    {
      "label": "Highlights",
      "href": "#products"
    },
    {
      "label": "Enquire",
      "href": "#enquiry"
    }
  ],
  "assets": {
    "collection": "restuarant",
    "root": "/assets/restuarant",
    "framesDirectory": "/assets/restuarant/frames",
    "productsDirectory": "/assets/restuarant/products"
  },
  "hero": {
    "directory": "/assets/restuarant/frames",
    "poster": "/assets/restuarant/frames/ezgif-frame-001.jpg",
    "filePrefix": "ezgif-frame-",
    "fileExtension": "jpg",
    "framePadding": 3,
    "firstFrame": 1,
    "frameCount": 300,
    "width": 1920,
    "height": 1080,
    "scrollHeightVh": 600,
    "maxDevicePixelRatio": 2,
    "maxCachedFrames": 48,
    "loadConcurrency": 6,
    "narrowViewportBreakpoint": 768,
    "focalPoint": {
      "wide": {
        "x": 0.5,
        "y": 0.5
      },
      "narrow": {
        "x": 0.62,
        "y": 0.5
      }
    },
    "chapters": [
      {
        "id": "opening",
        "from": 0,
        "to": 0.24,
        "align": "left",
        "showScrollCue": true,
        "eyebrow": "Antalia Restaurant",
        "heading": "A Levantine grill, warm Dubai welcome",
        "body": "In Al Quoz, Antalia brings charcoal-fired grills, mezze delights, and fresh juices to families, office teams, and delivery guests— Halal certified, open daily from noon to midnight."
      },
      {
        "id": "mid",
        "from": 0.34,
        "to": 0.6,
        "align": "right",
        "eyebrow": "Distinctive craft",
        "heading": "Carefully grilled, artfully shared",
        "body": "From smoky grills to vibrant mezze, every dish is crafted with heart. Our signature vegetarian platter and classic mezze are built for gatherings, big and small, with flavors that invite conversation."
      },
      {
        "id": "closing",
        "from": 0.72,
        "to": 1,
        "align": "left",
        "eyebrow": "Open invitation",
        "heading": "Dine in, take away, cater your moment",
        "body": "Whether you’re dining with family, refuelling after work, or planning a catered event, Antalia brings Levantine warmth to every table. Order now or preview the menu to plan your visit.",
        "primaryCta": {
          "label": "Order Now",
          "href": "#enquiry"
        },
        "secondaryCta": {
          "label": "View Menu",
          "href": "#products"
        }
      }
    ]
  },
  "productsSection": {
    "id": "products",
    "eyebrow": "Signature Plates",
    "heading": "Our plates to share, our flavors to remember",
    "body": "Explore a handpicked quartet that showcases Levantine flair—vegetarian depth, mezze brightness, roast with character, and fresh juice to pair.",
    "scrollHeightVh": 500,
    "imageAspectRatio": "1:1",
    "items": [
      {
        "category": "Platter",
        "name": "Signature Vegetarian Platter",
        "description": "A vibrant spread of Levantine veggies, grains, and dips designed for sharing, crafted in-house to celebrate vegetarian options.",
        "image": "signature-vegetarian-platter.jpg"
      },
      {
        "category": "Mezze",
        "name": "Fresh Mezze",
        "description": "A bright array of hummus, tabbouleh, baba ganoush, and more, prepared daily with herbs and zesty citrus.",
        "image": "fresh-mezze.jpg"
      },
      {
        "category": "Vegetables",
        "name": "Charcoal Roasted Cauliflower",
        "description": "Crisp-tender florets kissed with smoke and spice, a centerpiece that complements any table.",
        "image": "charcoal-roasted-cauliflower.jpg"
      },
      {
        "category": "Drinks",
        "name": "Fresh Juices",
        "description": "House-pressed blends to refresh your palate alongside your Levantine feast.",
        "image": "fresh-juices.jpg"
      }
    ]
  }
} satisfies SiteConfig;
